crm/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page

from crm.views import (
    CreateServiceView,
    CreateCampaignView,
    CreatePotentialClientView,
    CreateContractView,
    CreateActiveClientView,

    ServiceListView,
    CampaignListView,
    PotentialClientListView,
    ContractListView,
    ActiveClientListView,

    ServiceDetailView,
    CampaignDetailView,
    PotentialClientDetailView,
    ContractDetailView,
    ActiveClientDetailView,

    ServiceDeleteView,
    CampaignDeleteView,
    PotentialClientDeleteView,
    ContractDeleteView,
    ActiveClientDeleteView,

    ServiceUpdateView,
    CampaignUpdateView,
    PotentialClientUpdateView,
    ContractUpdateView,
    ActiveClientUpdateView,

    StatisticsView,
)

app_name = "crm"

urlpatterns = [
    path("create-service/", CreateServiceView.as_view(), name="create_service"),
    path("create-campaign/", CreateCampaignView.as_view(), name="create_campaign"),
    path("create-potential-client/", CreatePotentialClientView.as_view(), name="create_potential_client"),
    path("create-contract/", CreateContractView.as_view(), name="create_contract"),
    path("create-active-client/<int:pk>", CreateActiveClientView.as_view(), name="create_active_client"),

    path("services/", ServiceListView.as_view(), name="services"),
    path("campaigns/", CampaignListView.as_view(), name="campaigns"),
    path("potential-clients/", PotentialClientListView.as_view(), name="potential_clients"),
    path("contracts/", ContractListView.as_view(), name="contracts"),
    path("active-clients/", ActiveClientListView.as_view(), name="active_clients"),

    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service_details"),
    path("campaigns/<int:pk>/", CampaignDetailView.as_view(), name="campaign_details"),
    path("potential-clients/<int:pk>/", PotentialClientDetailView.as_view(), name="potential_client_details"),
    path("contracts/<int:pk>/", ContractDetailView.as_view(), name="contract_details"),
    path("active-clients/<int:pk>/", ActiveClientDetailView.as_view(), name="active_client_details"),

    path("services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="service_delete"),
    path("campaigns/<int:pk>/delete/", CampaignDeleteView.as_view(), name="campaign_delete"),
    path("potential-clients/<int:pk>/delete/", PotentialClientDeleteView.as_view(), name="potential_client_delete"),
    path("contracts/<int:pk>/delete/", ContractDeleteView.as_view(), name="contract_delete"),
    path("active-clients/<int:pk>/delete/", ActiveClientDeleteView.as_view(), name="active_client_delete"),

    path("services/<int:pk>/update/", ServiceUpdateView.as_view(), name="service_update"),
    path("campaigns/<int:pk>/update/", CampaignUpdateView.as_view(), name="campaign_update"),
    path("potential-clients/<int:pk>/update/", PotentialClientUpdateView.as_view(), name="potential_client_update"),
    path("contracts/<int:pk>/update/", ContractUpdateView.as_view(), name="contract_update"),
    path("active-clients/<int:pk>/update/", ActiveClientUpdateView.as_view(), name="active_client_update"),

    path("statistics/", cache_page(settings.CACHE_TIME)(StatisticsView.as_view()), name="statistics"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crm.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )  # type: ignore

crm/models.py
from django.db import models


class Service(models.Model):
    """Модель услуги"""

    name = models.CharField(max_length=100, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    cost = models.DecimalField(max_digits=100, decimal_places=2, verbose_name="стоимость")

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return self.name


class Campaign(models.Model):
    """Модель рекламной компании"""

    name = models.CharField(max_length=100, verbose_name="название")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name="услуга")
    promotion_channel = models.CharField(max_length=100, verbose_name="канал продвижения")
    budget = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="бюджет")

    class Meta:
        verbose_name = "Рекламная компания"
        verbose_name_plural = "Рекламные компании"

    def __str__(self):
        return self.name


class PotentialClient(models.Model):
    """Модель потенциального клиента"""

    full_name = models.CharField(max_length=100, verbose_name="Ф.И.О")
    phone = models.CharField(max_length=11, verbose_name="телефон")
    email = models.EmailField(verbose_name="email")
    campaign = models.ForeignKey(
        Campaign,
        on_delete=models.CASCADE,
        verbose_name="рекламная кампания",
    )

    class Meta:
        verbose_name = "Потенциальный клиент"
        verbose_name_plural = "Потенциальные клиенты"

    def __str__(self):
        return self.full_name


class Contract(models.Model):
    """Модель контракта"""

    name = models.CharField(max_length=100, verbose_name="название")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name="услуга")
    document = models.FileField(upload_to="documents/", verbose_name="документ")
    conclusion_date = models.DateField(verbose_name="дата заключения")
    validity_period = models.PositiveIntegerField(verbose_name="период действия")
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="сумма")

    class Meta:
        verbose_name = "Контракт"
        verbose_name_plural = "Контракты"

    def __str__(self):
        return self.name


class ActiveClient(models.Model):
    """Модель активного клиента"""

    potential_client = models.OneToOneField(
        PotentialClient, on_delete=models.CASCADE, verbose_name="потенциальный клиент"
    )
    contract = models.OneToOneField(Contract, on_delete=models.CASCADE, verbose_name="контракт")

    class Meta:
        verbose_name = "Активный клиент"
        verbose_name_plural = "Активные клиенты"

    def __str__(self):
        return self.potential_client.full_name

crm/views.py
from decimal import Decimal
from typing import List, Tuple, Any, Dict, Literal

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ImproperlyConfigured
from django.db.models import QuerySet, Sum
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    TemplateView,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)

from crm.models import (
    Service,
    Campaign,
    PotentialClient,
    Contract,
    ActiveClient,
)


# PERMISSIONS GROUP CLASSES
class GroupRequiredMixin(UserPassesTestMixin):
    """Миксин проверки наличия пользователя в указанной группе прав group_names"""

    group_names: List[str] = []

    def test_func(self):
        if not self.group_names:
            raise ImproperlyConfigured("Необходимо установить group_names в вашем представлении")
        user_groups: List[str] = self.request.user.groups.values_list("name", flat=True)
        return any(group_name in user_groups for group_name in self.group_names)


class SuperUserRequiredMixin(UserPassesTestMixin):
    """Миксин проверки пользователя на статус суперпользователя"""

    def test_func(self):
        return self.request.user.is_superuser


# CREATE VIEWS
class CreateServiceView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    """Представление создания услуги"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Service
    fields: Literal["__all__"] = "__all__"
    success_url = reverse_lazy("crm:services")


class CreateCampaignView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    """Представление создания рекламной компании"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Campaign
    fields: Literal["__all__"] = "__all__"
    success_url = reverse_lazy("crm:campaigns")


class CreatePotentialClientView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    """Представление создания потенциального клиента"""

    group_names: List[str] = [
        "Operator",
    ]
    model = PotentialClient
    fields: Literal["__all__"] = "__all__"
    success_url = reverse_lazy("crm:potential_clients")


class CreateContractView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    """Представление создания контракта"""

    group_names: List[str] = [
        "Manager",
    ]
    model = Contract
    fields: Literal["__all__"] = "__all__"
    success_url = reverse_lazy("crm:contracts")


class CreateActiveClientView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    """Представление создания активного клиента"""

    group_names: List[str] = [
        "Manager",
    ]
    model = ActiveClient
    fields: Tuple[str] = ("contract",)
    success_url = reverse_lazy("crm:active_clients")

    def form_valid(self, form):
        potential_client_id: int = self.kwargs.get("pk")
        form.instance.potential_client = PotentialClient.objects.get(pk=potential_client_id)
        return super().form_valid(form)


# LIST VIEWS
class ServiceListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    """Представление списка услуг"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Service


class CampaignListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    """Представление списка рекламной компании"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Campaign


class PotentialClientListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    """Представление списка потенциальных клиентов"""

    group_names: List[str] = ["Operator", "Manager"]
    model = PotentialClient

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        potential_clients = self.get_queryset()

        active_clients: QuerySet = ActiveClient.objects.filter(potential_client__in=potential_clients)
        active_clients_ids: List[int] = active_clients.values_list("potential_client_id", flat=True)

        context["active_clients_ids"] = active_clients_ids
        return context


class ContractListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    """Представление списка контраков"""

    group_names: List[str] = [
        "Manager",
    ]
    model = Contract


class ActiveClientListView(LoginRequiredMixin, SuperUserRequiredMixin, ListView):
    """Представление списка активных клиентов"""

    queryset = ActiveClient.objects.select_related("potential_client")


# DETAIL VIEWS
class ServiceDetailView(LoginRequiredMixin, GroupRequiredMixin, DetailView):
    """Представление списка деталей услуги"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Service


class CampaignDetailView(LoginRequiredMixin, GroupRequiredMixin, DetailView):
    """Представление списка деталей рекламной компании"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Campaign


class PotentialClientDetailView(LoginRequiredMixin, GroupRequiredMixin, DetailView):
    """Представление списка деталей потенциального клиента"""

    group_names: List[str] = [
        "Operator",
    ]
    model = PotentialClient


class ContractDetailView(LoginRequiredMixin, GroupRequiredMixin, DetailView):
    """Представление списка деталей контракта"""

    group_names: List[str] = [
        "Manager",
    ]
    model = Contract


class ActiveClientDetailView(LoginRequiredMixin, SuperUserRequiredMixin, DetailView):
    """Представление списка деталей активного клиента"""

    model = ActiveClient


# DELETE VIEWS
class ServiceDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, DeleteView):  # type: ignore
    """Представление удаления услуги"""

    model = Service
    success_url = reverse_lazy("crm:services")


class CampaignDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, DeleteView):  # type: ignore
    """Представление удаления рекламной компании"""

    model = Campaign
    success_url = reverse_lazy("crm:campaigns")


class PotentialClientDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, DeleteView):  # type: ignore
    """Представление удаления потенциального клиента"""

    model = PotentialClient
    success_url = reverse_lazy("crm:potential_clients")


class ContractDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, DeleteView):  # type: ignore
    """Представление удаления контракта"""

    model = Contract
    success_url = reverse_lazy("crm:contracts")


class ActiveClientDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, DeleteView):  # type: ignore
    """Представление удаления активного клиента"""

    model = ActiveClient
    success_url = reverse_lazy("crm:active_clients")


# UPDATE VIEWS
class ServiceUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    """Представление редактирования услуги"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Service
    fields: Literal["__all__"] = "__all__"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("crm:services")


class CampaignUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    """Представление редактирования рекламной компании"""

    group_names: List[str] = [
        "Marketer",
    ]
    model = Campaign
    fields: Literal["__all__"] = "__all__"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("crm:campaigns")


class PotentialClientUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    """Представление редактирования потенциального клиента"""

    group_names: List[str] = [
        "Operator",
    ]
    model = PotentialClient
    fields: Literal["__all__"] = "__all__"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("crm:potential_clients")


class ContractUpdateView(LoginRequiredMixin, GroupRequiredMixin, UpdateView):
    """Представление редактирования контракта"""

    group_names: List[str] = [
        "Manager",
    ]
    model = Contract
    fields: Literal["__all__"] = "__all__"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("crm:contracts")


class ActiveClientUpdateView(LoginRequiredMixin, SuperUserRequiredMixin, UpdateView):
    """Представление редактирования активного клиента"""

    model = ActiveClient
    fields: Literal["__all__"] = "__all__"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("crm:active_clients")


class StatisticsView(LoginRequiredMixin, TemplateView):
    """Представление статистики"""

    template_name = "crm/statistics.html"

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        potential_clients: int = PotentialClient.objects.count()
        active_clients: int = ActiveClient.objects.count()
        total_income: Decimal = Contract.objects.aggregate(Sum('amount')).get('amount__sum')
        total_expenses: Decimal = Campaign.objects.aggregate(Sum('budget')).get('budget__sum')

        income_expenses_ratio: Decimal = round((total_income / total_expenses if total_income > 0 else 0), 2)

        context["potential_clients"] = potential_clients
        context["active_clients"] = active_clients
        context["income_expenses_ratio"] = income_expenses_ratio

        return context

crm/templates/crm/activeclient_detail.html
{% extends 'crm/base.html' %}

{% block title %}
  {{ object.name }} details
{% endblock %}

{% block body %}
  <h1>Active client #{{ object.pk }}</h1>

  <ul>
    <li>Potential client: {{ object.potential_client }}</li>
    <li>Contract: {{ object.contract }}</li>
  </ul>

  <br>
  <div>
    <a href="{% url 'crm:active_client_update' pk=object.pk %}">Update active client</a>
  </div>
  <div>
    <a href="{% url 'crm:active_client_delete' pk=object.pk %}">Delete active client</a>
  </div>
  <div>
    <a href="{% url 'crm:active_clients' %}">Back to active clients</a>
  </div>
{% endblock %}

crm/templates/crm/activeclient_list.html
{% extends 'crm/base.html' %}

{% block title %}
  Active clients
{% endblock %}

{% block body %}
  <h1>Active clients</h1>

  <ul>
    {% for active_client in object_list %}
      <li><a
          href="{% url 'crm:active_client_details' pk=active_client.pk %}">{{ active_client.potential_client.full_name }}</a>
      </li>
      <a href="{% url 'crm:active_client_delete' pk=active_client.pk %}">Delete active client</a>
    {% empty %}
      <li>No active clients yet</li>
    {% endfor %}
  </ul>
{% endblock %}

crm/templates/crm/advertisingcampaign_confirm_delete.html
{% extends 'crm/base.html' %}

{% block title %}
  Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete {{ object.name }}?</h1>
  <div>
    <a href="{% url 'crm:advertising_campaign_details' pk=object.pk %}">
      Back to advertising campaign
    </a>
  </div>
  <br>
  <div>
    {% include 'crm/delete_form.html' %}
  </div>
{% endblock %}

crm/templates/crm/advertisingcampaign_detail.html
{% extends 'crm/base.html' %}

{% block title %}
  {{ object.name }} details
{% endblock %}

{% block body %}
  <h1>Advertising campaign #{{ object.pk }}</h1>

  <ul>
    <li>Name: {{ object.name }}</li>
    <li>Service: {{ object.service }}</li>
    <li>Promotion channel: {{ object.promotion_channel }}</li>
    <li>Budget: {{ object.budget }}</li>
  </ul>
  <br>
  <div>
    <a href="{% url 'crm:advertising_campaign_update' pk=object.pk %}">Update advertising campaign</a>
  </div>
  <div>
    <a href="{% url 'crm:advertising_campaign_delete' pk=object.pk %}">Delete advertising campaign</a>
  </div>
  <div>
    <a href="{% url 'crm:advertising_campaigns' %}">Back to advertising campaigns</a>
  </div>
{% endblock %}

crm/templates/crm/advertisingcampaign_list.html
{% extends 'crm/base.html' %}

{% block title %}
  Advertising campaigns
{% endblock %}

{% block body %}
  <h1>Advertising campaigns</h1>

  <ul>
    {% for campaign in object_list %}
      <li><a href="{% url 'crm:advertising_campaign_details' pk=campaign.pk %}">{{ campaign.name }}</a></li>
      <a href="{% url 'crm:advertising_campaign_delete' pk=campaign.pk %}">Delete campaign</a>
    {% empty %}
      <li>No advertising campaigns yet</li>
    {% endfor %}
  </ul>
  <br>
  <div>
    <a href="{% url 'crm:create_advertising_campaign' %}">Create a new advertising campaign</a>
  </div>
{% endblock %}

crm/templates/crm/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

crm/templates/crm/campaign_detail.html
{% extends 'crm/base.html' %}

{% block title %}
  {{ object.name }} details
{% endblock %}

{% block body %}
  <h1>Advertising campaign #{{ object.pk }}</h1>

  <ul>
    <li>Name: {{ object.name }}</li>
    <li>Service: {{ object.service }}</li>
    <li>Promotion channel: {{ object.promotion_channel }}</li>
    <li>Budget: {{ object.budget }}</li>
  </ul>
  <br>
  <div>
    <a href="{% url 'crm:campaign_update' pk=object.pk %}">Update advertising campaign</a>
  </div>
  <div>
    <a href="{% url 'crm:campaign_delete' pk=object.pk %}">Delete advertising campaign</a>
  </div>
  <div>
    <a href="{% url 'crm:campaigns' %}">Back to advertising campaigns</a>
  </div>
{% endblock %}

crm/templates/crm/delete_form.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Delete</button>
</form>

crm/templates/crm/potentialclient_detail.html
{% extends 'crm/base.html' %}

{% block title %}
  {{ object.name }} details
{% endblock %}

{% block body %}
  <h1>Potential client #{{ object.pk }}</h1>

  <ul>
    <li>Full name: {{ object.full_name }}</li>
    <li>Phone: {{ object.phone }}</li>
    <li>Email: {{ object.email }}</li>
    <li>Advertising campaign: {{ object.campaign }}</li>
  </ul>

  <br>
  <div>
    <a href="{% url 'crm:potential_client_update' pk=object.pk %}">Update potential client</a>
  </div>
  <div>
    <a href="{% url 'crm:potential_client_delete' pk=object.pk %}">Delete potential client</a>
  </div>
  <div>
    <a href="{% url 'crm:potential_clients' %}">Back to potential clients</a>
  </div>
{% endblock %}

crm/templates/crm/potentialclient_list.html
{% extends 'crm/base.html' %}

{% block title %}
  Potential clients
{% endblock %}

{% block body %}
  <h1>Potential clients</h1>

  <ul>
    {% for potential_client in object_list %}
      <li><a href="{% url 'crm:potential_client_details' pk=potential_client.pk %}">{{ potential_client.full_name }}</a>
      </li>
      <a href="{% url 'crm:potential_client_delete' pk=potential_client.pk %}">Delete potential client</a>
      {% if potential_client.id not in active_clients_ids %}
        <br>
        <a href="{% url 'crm:create_active_client' pk=potential_client.pk %}">Convert to active client</a>
      {% endif %}
    {% empty %}
      <li>No potential clients yet</li>
    {% endfor %}
  </ul>
  <br>
  <div>
    <a href="{% url 'crm:create_potential_client' %}">Create a new potential client</a>
  </div>
{% endblock %}

crm/templates/crm/potentialclient_update_form.html
{% extends 'crm/base.html' %}

{% block title %}
  Update {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Update {{ object.name }}</h1>
  <div>
    {% include 'crm/update_form.html' %}
  </div>
  <br>
  <div>
    <a href="{% url 'crm:potential_client_details' pk=object.pk %}">
      Back to potential client
    </a>
  </div>
{% endblock %}

crm/templates/crm/service_form.html
{% extends 'crm/base.html' %}

{% block title %}
  Create service
{% endblock %}

{% block body %}
  <h1>Create service</h1>
  {% include 'crm/create_form.html' %}
{% endblock %}

crm/templates/crm/service_list.html
{% extends 'crm/base.html' %}

{% block title %}
  Services
{% endblock %}

{% block body %}
  <h1>Services</h1>

  <ul>
    {% for service in object_list %}
      <li>
        <a href="{% url 'crm:service_details' pk=service.pk %}">{{ service.name }}</a>
      </li>
      <a href="{% url 'crm:service_delete' pk=service.pk %}">Delete service</a>
    {% empty %}
      <li>No services yet</li>
    {% endfor %}
  </ul>
  <br>
  <div>
    <a href="{% url 'crm:create_service' %}">Create a new service</a>
  </div>
{% endblock %}

crm/templates/crm/statistics.html
{% extends 'crm/base.html' %}

{% block title %}
  Statistics
{% endblock %}

{% block body %}
  <h1>Statistics</h1>

  <ul>
    <li>Total clients attracted: {{ potential_clients }}</li>
    <li>Total active clients: {{ active_clients }}</li>
    <li>Income-expenses ratio: {{ income_expenses_ratio }}</li>
  </ul>
{% endblock %}